(() => {
  const messages = {
    en: {
      language:"Language", loginHint:"Sign in with the NASDrop ID and password configured on this server. Opening the DSM icon signs in automatically.", httpWarningTitle:"Unencrypted HTTP connection", httpWarningBody:"Your NASDrop ID, password, and session are not encrypted. Use HTTP only on a trusted network; configure HTTPS for internet access.", username:"ID", password:"Password", openDashboard:"Open dashboard", accountNotConfigured:"No account is configured. Use the DSM icon or the Docker account command to create an ID and password first.", logout:"Sign out",
      dashboard:"Dashboard", settings:"Settings", runningOnNas:"Running on NAS", downloads:"Downloads", linkLabel:"Supported services: GigaFile · GoFile · Pixeldrain · Buzzheavier", downloadNow:"Download to NAS",
      destination:"Destination", checking:"Checking…", checkingShort:"Checking", chooseFolder:"Choose folder", jobs:"Jobs", loading:"Loading…", clearCompleted:"Clear completed",
      selected:"{count} selected", selectAll:"Select all", clearSelection:"Clear selection", pause:"Pause", resume:"Resume", delete:"Delete",
      clientConnection:"Client connection", accountHint:"Direct browsers and client apps sign in with this ID and password. The DSM icon continues to sign in automatically.", currentPassword:"Current password", newPassword:"New password", confirmPassword:"Confirm new password", passwordRules:"Use 10–128 characters. Passwords are stored only as a salted hash.", saveAccount:"Save ID and password", resetAccount:"Reset", resetAccountHint:"Enter a new ID and password, then save them. Existing client sessions will be signed out.", passwordMismatch:"The new passwords do not match.", accountSaved:"The client login ID and password were saved.",
      defaultFolder:"Default destination", defaultFolderHint:"Jobs are saved here unless another folder is selected.", change:"Change", parallelTitle:"Parallel downloads from the same service",
      parallelHint:"Off by default. When enabled, multiple jobs from services such as GoFile may start together.", allowParallel:"Allow parallel downloads", sameServiceMax:"Maximum per service",
      twoJobs:"2 jobs", threeJobs:"3 jobs", warning:"Warning", parallelWarning:"In 8-part mode, each job can use up to 8 connections. Three active jobs may create up to 24 connections, increasing rate-limit risk and NAS CPU, disk, and network load.",
      off:"Off", saveParallel:"Save parallel-download settings", folderPermissions:"Folder permissions", folderPermissionsHint:"Locked shared folders are not accessible. In DSM Shared Folder permissions, grant read/write access to this package's internal system user.",
      serviceAccount:"Service account", serviceAddress:"Connection path", serviceAddressHint:"The public router port, DSM reverse proxy port, and NASDrop internal port have different roles.", accessMethodHint:"The DSM icon signs in automatically. Direct browser access and client apps must enter the ID and password.", version:"Version", currentAccessAddress:"Current address", launcherAddress:"DSM icon address on this hostname",
      launcherPort:"Public router port (DSM icon address)", launcherPortHint:"This is the port visible on the internet, not DSM's reverse proxy source port or NASDrop's internal port.", connectionRouteTitle:"Reverse proxy route example", connectionRoute:"Internet :{publicPort} → router → DSM HTTPS port configured in the proxy rule → DSM reverse proxy → NASDrop HTTP :{appPort}", connectionRouteHint:"Even if both ends use 8791, the public router port and NASDrop internal port are separate roles.", saveLauncherPort:"Save icon port", launcherPortSaved:"The DSM icon will use external port {port}.",
      reverseProxyMode:"Trust client IP from DSM reverse proxy", reverseProxyHint:"Enable when the router sends the public port to DSM HTTPS and DSM then proxies to NASDrop HTTP port 8791. LAN access to 192.168.x.x:8791 can remain available.", proxyDetectedTitle:"Reverse proxy detected", proxyDetectedWarning:"Clients currently share one login-throttle bucket. Enable this after confirming the router does not forward directly to NASDrop port 8791.", proxyEnabledWarning:"The public router port must lead to DSM's reverse proxy source port, not directly to NASDrop's internal port 8791.", confirmReverseProxy:"Trust client addresses supplied by DSM reverse proxy? Continue only if the router's public port leads to DSM's proxy source port, not directly to NASDrop port 8791.", saveConnectionSettings:"Save connection settings", connectionSettingsSaved:"Connection settings were saved. The DSM icon will use public router port {port}.",
      downloadMethod:"Per-file download method", downloadMethodHint:"Single connection avoids splitting and merging while keeping the shared integrity checks.", method:"Method", segmentedMode:"8-part download + verification", singleMode:"Single connection + verification",
      singleModeWarningTitle:"Single-connection trade-off", singleModeWarning:"One connection lowers provider request pressure. The completed file is still size-checked and hashed, so disk reading continues during verification.", saveDownloadMethod:"Save download method", singleModeShort:"Single connection", segmentedModeShort:"8 parts + verification", downloadBehavior:"Download behavior", downloadBehaviorHint:"Configure concurrency and the connection method in one place.", combinedDownloadWarning:"Parallel or 8-part downloads can increase NAS and network load.", saveDownloadBehavior:"Save download behavior", downloadBehaviorSaved:"Download behavior settings were saved.",
      sponsorTitle:"Support NASDrop", sponsorHint:"If NASDrop is useful to you, you can support its continued development on GitHub Sponsors.", sponsorAction:"Sponsor on GitHub",
      folderTitle:"Choose destination folder", close:"Close", up:"Up", cancel:"Cancel", chooseThisFolder:"Choose this folder", requestFailed:"The request could not be completed.",
      error_auth_required:"Sign in to continue.", error_invalid_credentials:"The ID or password is incorrect.", error_account_not_configured:"No NASDrop account is configured yet.", error_current_password_invalid:"The current password is incorrect.", error_launcher_expired:"The DSM icon connection expired. Open the icon again.", error_permission_denied:"The package account does not have permission for this folder.", error_password_required:"An archive password is required or the password is incorrect.", error_rate_limited:"The download service is temporarily rate-limiting requests. Please try again later.", error_network_error:"Could not connect to the download service.", error_link_expired:"The link expired or is no longer available. Add a fresh link.", error_integrity_failed:"Integrity verification failed. Damaged temporary data was removed.", error_archive_error:"The archive could not be processed safely.", error_invalid_link:"This is not a supported download link.", error_invalid_job_state:"This job cannot perform that action in its current state.", error_invalid_request:"Check the entered values and try again.", error_not_found:"The requested item was not found.", error_service_restarted:"The service restarted and paused this job. It can be resumed.", error_internal_error:"An internal error occurred.", error_generic_error:"The request could not be completed.",
      error_invalid_username:"Use 3–32 characters: English letters, numbers, periods, underscores, or hyphens.", error_invalid_password:"Use a password of 10–128 characters without control characters.", error_too_many_attempts:"Too many sign-in attempts. Try again in about {minutes} minutes.",
      error_login_temporarily_limited:"Sign-in traffic is temporarily limited. Try again in {seconds} seconds.",
      statusQueued:"Queued", statusReady:"Ready", statusDownloading:"Downloading", statusWaitingProcessing:"Waiting for disk processing", statusVerifying:"Verifying", statusExtracting:"Extracting", statusPublishing:"Moving to destination", statusPasswordRequired:"Password required", statusPaused:"Paused", statusCompleted:"Completed", statusFailed:"Error", statusCancelled:"Stopped",
      writable:"Writable", permissionRequired:"Permission required", notSelected:"Not selected", packageWritable:"Package account can write", dedicatedAccount:"Dedicated package account",
      gofileCooldown:"GoFile protection pause · automatically resumes after {time}. Do not retry repeatedly.", sameServiceSummary:"Up to {count} from the same service", qrAlt:"NASDrop client connection QR", qrFailed:"Could not create QR: {error}",
      processing:"{count} processing", noQueuedJobs:"No queued jobs", noJobsTitle:"No download jobs.", noJobsHint:"Add a link to manage its progress here.", scheduled:"Scheduled", integrity:"File verification details",
      confirmDelete:"Delete the {count} selected job records?", inspectLink:"Checking the link…", addedMany:"Added {count} files to the {target} queue.", addedOne:"Added {name} to the {target} queue.",
      confirmClear:"Delete all {count} completed job records?", confirmParallel:"Run up to {count} jobs from the same service at once? Rate limiting and NAS load may increase.", saving:"Saving…",
      parallelSaved:"Up to {count} jobs from the same service can now run together.", sequentialSaved:"Jobs from the same service will run one at a time.", loadingFolders:"Loading folders…",
      confirmSingleMode:"Use single-connection downloads? Provider request pressure is reduced while final integrity verification remains enabled.", singleModeSaved:"New and resumed jobs will use one connection and final integrity verification.", segmentedModeSaved:"New and resumed jobs will use 8 parts and full verification.",
      currentWritable:"Files can be saved in this folder.", currentNotWritable:"This location cannot be selected. Choose a writable subfolder.", browse:"Browse", noSubfolders:"No subfolders to display.",
      processingTitle:"Temporary workspace and extraction", processingHint:"Parts are downloaded and combined in a hidden workspace. Only completed results appear in the destination.", temporaryFolder:"Temporary folder", archiveEngine:"Archive engine", engineReady:"7-Zip ready", engineMissing:"Engine missing", autoExtract:"Use extraction by default for new jobs", diskProtection:"Pause new downloads during disk processing", archiveFormats:"ZIP, AES ZIP, 7z, RAR, and TAR-family archives are extracted into a folder named after the archive.", saveProcessing:"Save processing settings", autoExtractOn:"Default extraction on", autoExtractOff:"Default extraction off", processingSavedOn:"New jobs will default to extraction; each job can override it.", processingSavedOff:"New jobs will default to keeping archive files.", archiveExtracted:"Archive extracted · original archive kept only in the temporary workspace", extractThisJob:"Extract archives after download", archivePasswordOptional:"Archive password (optional)", archivePassword:"Archive password", retryExtraction:"Retry extraction",
      defaultChanged:"Default destination changed to {target}."
    },
    ko: {
      language:"언어", loginHint:"이 서버에 설정한 NASDrop ID와 비밀번호로 로그인하세요. DSM 아이콘으로 열면 자동 로그인됩니다.", httpWarningTitle:"암호화되지 않은 HTTP 연결", httpWarningBody:"NASDrop ID, 비밀번호와 세션이 암호화되지 않습니다. 신뢰할 수 있는 네트워크에서만 HTTP를 사용하고, 인터넷 접속에는 HTTPS를 설정하세요.", username:"ID", password:"비밀번호", openDashboard:"대시보드 열기", accountNotConfigured:"아직 계정이 설정되지 않았습니다. DSM 아이콘 또는 Docker 계정 설정 명령으로 ID와 비밀번호를 먼저 만드세요.", logout:"로그아웃",
      dashboard:"대시보드", settings:"설정", runningOnNas:"NAS에서 실행 중", downloads:"다운로드", linkLabel:"지원 서비스: GigaFile · GoFile · Pixeldrain · Buzzheavier", downloadNow:"NAS로 바로 다운로드",
      destination:"저장 위치", checking:"확인 중…", checkingShort:"검사 중", chooseFolder:"폴더 선택", jobs:"작업 목록", loading:"불러오는 중…", clearCompleted:"완료 항목 정리",
      selected:"{count}개 선택", selectAll:"전체 선택", clearSelection:"선택 해제", pause:"일시정지", resume:"재개", delete:"삭제",
      clientConnection:"클라이언트 연결", accountHint:"주소를 직접 연 브라우저와 클라이언트 앱은 이 ID와 비밀번호로 로그인합니다. DSM 아이콘은 계속 자동 로그인됩니다.", currentPassword:"현재 비밀번호", newPassword:"새 비밀번호", confirmPassword:"새 비밀번호 확인", passwordRules:"10~128자를 사용하세요. 비밀번호 원문은 저장하지 않고 솔트를 적용한 해시만 저장합니다.", saveAccount:"ID와 비밀번호 저장", resetAccount:"재설정", resetAccountHint:"새 ID와 비밀번호를 입력한 뒤 저장하세요. 기존 클라이언트는 모두 로그아웃됩니다.", passwordMismatch:"새 비밀번호가 서로 일치하지 않습니다.", accountSaved:"클라이언트 로그인 ID와 비밀번호를 저장했습니다.",
      defaultFolder:"기본 저장 폴더", defaultFolderHint:"작업에서 폴더를 따로 고르지 않으면 이 위치에 저장합니다.", change:"변경", parallelTitle:"같은 서비스 동시 다운로드",
      parallelHint:"기본값은 꺼짐입니다. 켜면 GoFile 등 같은 서비스의 여러 작업을 함께 시작합니다.", allowParallel:"동시 다운로드 허용", sameServiceMax:"같은 서비스 최대",
      twoJobs:"2개", threeJobs:"3개", warning:"주의", parallelWarning:"8분할 방식에서는 작업 하나가 최대 8개 연결을 사용하므로 전체 3개 실행 시 최대 24개 연결이 생길 수 있습니다. 속도 제한·일시 차단 및 NAS CPU·디스크·네트워크 부하가 증가할 수 있습니다.",
      off:"꺼짐", saveParallel:"동시 다운로드 설정 저장", folderPermissions:"폴더 접근 권한", folderPermissionsHint:"권한이 없는 공유 폴더는 잠금 표시됩니다. DSM 공유 폴더 권한에서 이 패키지의 시스템 내부 사용자에게 읽기/쓰기를 허용하세요.",
      serviceAccount:"서비스 계정", serviceAddress:"접속 경로", serviceAddressHint:"공유기 외부 포트, DSM 역방향 프록시 포트, NASDrop 내부 포트는 서로 역할이 다릅니다.", accessMethodHint:"DSM 아이콘은 자동 로그인됩니다. 주소를 직접 연 브라우저와 클라이언트 앱은 ID와 비밀번호를 입력해야 합니다.", version:"버전", currentAccessAddress:"현재 접속 주소", launcherAddress:"현재 호스트에서 DSM 아이콘이 열 주소",
      launcherPort:"공유기 외부 공개 포트 (DSM 아이콘 주소)", launcherPortHint:"인터넷에 보이는 포트입니다. DSM 역방향 프록시의 소스 포트나 NASDrop 내부 포트를 입력하는 칸이 아닙니다.", connectionRouteTitle:"역방향 프록시 전달 예시", connectionRoute:"인터넷 :{publicPort} → 공유기 → 프록시 규칙에 지정한 DSM HTTPS 포트 → DSM 역방향 프록시 → NASDrop HTTP :{appPort}", connectionRouteHint:"양쪽에 8791이 표시되더라도 공유기 외부 포트와 NASDrop 내부 포트는 서로 다른 역할입니다.", saveLauncherPort:"아이콘 포트 저장", launcherPortSaved:"DSM 아이콘이 외부 포트 {port}을(를) 사용합니다.",
      reverseProxyMode:"DSM 역방향 프록시가 전달한 실제 사용자 IP 신뢰", reverseProxyHint:"공유기의 외부 포트가 DSM HTTPS로 전달되고, DSM이 다시 NASDrop HTTP 8791로 전달할 때 켜세요. 내부망의 192.168.x.x:8791 직접 접속은 유지해도 됩니다.", proxyDetectedTitle:"역방향 프록시 감지됨", proxyDetectedWarning:"현재 모든 사용자가 하나의 로그인 차단 기록을 공유합니다. 공유기가 NASDrop 8791로 직접 전달하지 않는지 확인한 뒤 이 설정을 켜세요.", proxyEnabledWarning:"공유기의 외부 공개 포트는 NASDrop 내부 8791이 아니라 DSM 역방향 프록시의 소스 포트로 전달되어야 합니다.", confirmReverseProxy:"DSM 역방향 프록시가 전달한 사용자 주소를 신뢰할까요? 공유기의 외부 포트가 NASDrop 8791이 아니라 DSM 프록시 소스 포트로 연결될 때만 계속하세요.", saveConnectionSettings:"연결 설정 저장", connectionSettingsSaved:"연결 설정을 저장했습니다. DSM 아이콘은 공유기 외부 포트 {port}을(를) 사용합니다.",
      downloadMethod:"파일별 다운로드 방식", downloadMethodHint:"단일 연결은 분할·병합을 생략하면서 공통 무결성 검사는 유지합니다.", method:"방식", segmentedMode:"8분할 다운로드 + 검증", singleMode:"단일 연결 + 검증",
      singleModeWarningTitle:"단일 연결 사용 시 주의", singleModeWarning:"한 개 연결로 서비스 요청 부담을 줄입니다. 완료 파일의 크기와 해시는 계속 검사하므로 검증 중 디스크 읽기는 발생합니다.", saveDownloadMethod:"다운로드 방식 저장", singleModeShort:"단일 연결", segmentedModeShort:"8분할 + 검증", downloadBehavior:"다운로드 동작", downloadBehaviorHint:"동시 실행 수와 파일별 연결 방식을 한곳에서 설정합니다.", combinedDownloadWarning:"동시 다운로드 또는 8분할 다운로드는 NAS와 네트워크에 부하를 높일 수 있습니다.", saveDownloadBehavior:"다운로드 동작 저장", downloadBehaviorSaved:"다운로드 동작 설정을 저장했습니다.",
      sponsorTitle:"NASDrop 후원", sponsorHint:"NASDrop이 유용했다면 GitHub Sponsors에서 지속적인 개발을 후원할 수 있습니다.", sponsorAction:"GitHub에서 후원하기",
      folderTitle:"저장 폴더 선택", close:"닫기", up:"상위", cancel:"취소", chooseThisFolder:"이 폴더 선택", requestFailed:"요청을 처리하지 못했습니다.",
      error_auth_required:"로그인이 필요합니다.", error_invalid_credentials:"ID 또는 비밀번호가 올바르지 않습니다.", error_account_not_configured:"아직 NASDrop 계정이 설정되지 않았습니다.", error_current_password_invalid:"현재 비밀번호가 올바르지 않습니다.", error_launcher_expired:"DSM 아이콘 연결이 만료되었습니다. 아이콘을 다시 열어 주세요.", error_permission_denied:"패키지 계정에 이 폴더의 권한이 없습니다.", error_password_required:"압축 암호가 필요하거나 입력한 암호가 올바르지 않습니다.", error_rate_limited:"다운로드 서비스가 요청을 일시 제한했습니다. 잠시 후 다시 시도해 주세요.", error_network_error:"다운로드 서비스에 연결하지 못했습니다.", error_link_expired:"링크가 만료됐거나 사용할 수 없습니다. 새 링크를 등록해 주세요.", error_integrity_failed:"무결성 검사에 실패하여 손상된 임시 데이터를 삭제했습니다.", error_archive_error:"압축 파일을 안전하게 처리하지 못했습니다.", error_invalid_link:"지원하는 다운로드 링크가 아닙니다.", error_invalid_job_state:"현재 상태에서는 이 작업을 수행할 수 없습니다.", error_invalid_request:"입력값을 확인한 뒤 다시 시도해 주세요.", error_not_found:"요청한 항목을 찾을 수 없습니다.", error_service_restarted:"서비스가 재시작되어 작업을 일시정지했습니다. 다시 시작할 수 있습니다.", error_internal_error:"내부 처리 중 오류가 발생했습니다.", error_generic_error:"요청을 처리하지 못했습니다.",
      error_invalid_username:"ID는 영문·숫자·마침표·밑줄·하이픈을 사용해 3~32자로 입력하세요.", error_invalid_password:"비밀번호는 제어 문자 없이 10~128자로 입력하세요.", error_too_many_attempts:"로그인 시도가 너무 많습니다. 약 {minutes}분 후 다시 시도하세요.",
      error_login_temporarily_limited:"로그인 요청이 잠시 제한되었습니다. {seconds}초 후 다시 시도하세요.",
      statusQueued:"대기 중", statusReady:"준비", statusDownloading:"다운로드 중", statusWaitingProcessing:"디스크 작업 대기", statusVerifying:"검증 중", statusExtracting:"압축 해제 중", statusPublishing:"최종 폴더로 이동 중", statusPasswordRequired:"암호 입력 필요", statusPaused:"일시정지", statusCompleted:"완료", statusFailed:"오류", statusCancelled:"중지됨",
      writable:"쓰기 가능", permissionRequired:"권한 필요", notSelected:"선택되지 않음", packageWritable:"패키지 계정 쓰기 가능", dedicatedAccount:"패키지 전용 계정",
      gofileCooldown:"GoFile 보호 대기 중 · {time} 이후 자동 해제됩니다. 반복 시도하지 마세요.", sameServiceSummary:"같은 서비스 최대 {count}개", qrAlt:"NASDrop 클라이언트 연결 QR", qrFailed:"QR 생성 실패: {error}",
      processing:"{count}개 처리 중", noQueuedJobs:"대기 중인 작업 없음", noJobsTitle:"다운로드 작업이 없습니다.", noJobsHint:"링크를 추가하면 이곳에서 진행 상태를 관리할 수 있습니다.", scheduled:"예약 대기", integrity:"파일 검증 정보",
      confirmDelete:"선택한 {count}개 작업 기록을 삭제할까요?", inspectLink:"링크를 확인하는 중…", addedMany:"{count}개 파일을 {target} 대기열에 추가했습니다.", addedOne:"{name} 파일을 {target} 대기열에 추가했습니다.",
      confirmClear:"완료된 {count}개 작업 기록을 모두 삭제할까요?", confirmParallel:"같은 서비스 작업을 최대 {count}개 동시에 실행할까요? 속도 제한·일시 차단 및 NAS 부하가 증가할 수 있습니다.", saving:"저장하는 중…",
      parallelSaved:"같은 서비스 동시 다운로드를 최대 {count}개로 설정했습니다.", sequentialSaved:"같은 서비스 작업은 한 번에 하나씩 실행합니다.", loadingFolders:"폴더를 불러오는 중…",
      confirmSingleMode:"단일 연결 다운로드를 사용할까요? 서비스 요청 부담은 줄이고 최종 무결성 검사는 유지합니다.", singleModeSaved:"새 작업과 재개 작업은 단일 연결과 최종 무결성 검사를 사용합니다.", segmentedModeSaved:"새 작업과 재개 작업은 8분할 다운로드와 전체 검증을 사용합니다.",
      currentWritable:"현재 폴더에 저장할 수 있습니다.", currentNotWritable:"현재 위치는 선택할 수 없습니다. 쓰기 가능한 하위 폴더를 선택하세요.", browse:"탐색", noSubfolders:"표시할 하위 폴더가 없습니다.",
      processingTitle:"임시 폴더 및 압축 해제", processingHint:"파일 조각은 숨김 임시 폴더에서 다운로드·결합되며 완성된 결과만 저장 폴더에 나타납니다.", temporaryFolder:"임시 폴더", archiveEngine:"압축 해제 엔진", engineReady:"7-Zip 준비됨", engineMissing:"엔진 없음", autoExtract:"새 작업의 압축 해제 기본값", diskProtection:"디스크 처리 중 새 다운로드 일시 정지", archiveFormats:"ZIP·AES ZIP·7z·RAR·TAR 계열 압축을 압축파일명과 같은 폴더로 안전하게 해제합니다.", saveProcessing:"처리 설정 저장", autoExtractOn:"기본 압축 해제 켜짐", autoExtractOff:"기본 압축 해제 꺼짐", processingSavedOn:"새 작업은 압축 해제가 기본이며 작업마다 변경할 수 있습니다.", processingSavedOff:"새 작업은 압축파일 보존이 기본입니다.", archiveExtracted:"압축 해제 완료 · 원본 압축 파일은 임시 공간에서만 사용됨", extractThisJob:"다운로드 후 압축 해제", archivePasswordOptional:"압축 암호(선택 사항)", archivePassword:"압축 암호", retryExtraction:"압축 해제 재시도",
      defaultChanged:"기본 저장 폴더를 {target}(으)로 변경했습니다."
    },
    ja: {
      language:"言語", loginHint:"このサーバーで設定したNASDropのIDとパスワードでログインしてください。DSMアイコンから開くと自動でログインします。", httpWarningTitle:"暗号化されていないHTTP接続", httpWarningBody:"NASDropのID、パスワード、セッションは暗号化されません。HTTPは信頼できるネットワーク内だけで使用し、インターネット接続にはHTTPSを設定してください。", username:"ID", password:"パスワード", openDashboard:"ダッシュボードを開く", accountNotConfigured:"アカウントがまだ設定されていません。DSMアイコンまたはDockerのアカウント設定コマンドでIDとパスワードを作成してください。", logout:"ログアウト",
      dashboard:"ダッシュボード", settings:"設定", runningOnNas:"NASで実行中", downloads:"ダウンロード", linkLabel:"対応サービス: GigaFile · GoFile · Pixeldrain · Buzzheavier", downloadNow:"NASへダウンロード",
      destination:"保存先", checking:"確認中…", checkingShort:"確認中", chooseFolder:"フォルダーを選択", jobs:"ジョブ一覧", loading:"読み込み中…", clearCompleted:"完了項目を消去",
      selected:"{count}件選択", selectAll:"すべて選択", clearSelection:"選択解除", pause:"一時停止", resume:"再開", delete:"削除",
      clientConnection:"クライアント接続", accountHint:"直接開いたブラウザーとクライアントアプリは、このIDとパスワードでログインします。DSMアイコンは引き続き自動ログインします。", currentPassword:"現在のパスワード", newPassword:"新しいパスワード", confirmPassword:"新しいパスワードの確認", passwordRules:"10～128文字を使用してください。パスワードの原文は保存せず、ソルト付きハッシュのみ保存します。", saveAccount:"IDとパスワードを保存", resetAccount:"再設定", resetAccountHint:"新しいIDとパスワードを入力して保存してください。既存のクライアントセッションはすべてログアウトされます。", passwordMismatch:"新しいパスワードが一致しません。", accountSaved:"クライアントログイン用のIDとパスワードを保存しました。",
      defaultFolder:"既定の保存先", defaultFolderHint:"別のフォルダーを選ばない場合、ここに保存します。", change:"変更", parallelTitle:"同一サービスの並列ダウンロード",
      parallelHint:"既定ではオフです。有効にするとGoFileなど同じサービスの複数ジョブを同時に開始します。", allowParallel:"並列ダウンロードを許可", sameServiceMax:"サービスごとの最大数",
      twoJobs:"2件", threeJobs:"3件", warning:"注意", parallelWarning:"8分割方式では1ジョブが最大8接続を使用します。3ジョブでは最大24接続となり、速度制限や一時ブロック、NASのCPU・ディスク・ネットワーク負荷が増える場合があります。",
      off:"オフ", saveParallel:"並列設定を保存", folderPermissions:"フォルダー権限", folderPermissionsHint:"アクセスできない共有フォルダーはロック表示されます。DSMの共有フォルダー権限で、このパッケージの内部システムユーザーに読み書きを許可してください。",
      serviceAccount:"サービスアカウント", serviceAddress:"接続経路", serviceAddressHint:"ルーターの公開ポート、DSMリバースプロキシのポート、NASDropの内部ポートは役割が異なります。", accessMethodHint:"DSMアイコンは自動ログインします。直接開いたブラウザーとクライアントアプリではIDとパスワードを入力してください。", version:"バージョン", currentAccessAddress:"現在の接続アドレス", launcherAddress:"このホストでDSMアイコンが開くアドレス",
      launcherPort:"ルーターの公開ポート（DSMアイコンのアドレス）", launcherPortHint:"インターネット側に見えるポートです。DSMリバースプロキシのソースポートやNASDrop内部ポートではありません。", connectionRouteTitle:"リバースプロキシ経路の例", connectionRoute:"インターネット :{publicPort} → ルーター → プロキシ規則で設定したDSM HTTPSポート → DSMリバースプロキシ → NASDrop HTTP :{appPort}", connectionRouteHint:"両端が8791でも、ルーターの公開ポートとNASDrop内部ポートは別の役割です。", saveLauncherPort:"アイコンポートを保存", launcherPortSaved:"DSMアイコンは外部ポート{port}を使用します。",
      reverseProxyMode:"DSMリバースプロキシが転送した実クライアントIPを信頼", reverseProxyHint:"ルーターの公開ポートがDSM HTTPSへ転送され、DSMがNASDrop HTTP 8791へプロキシする場合に有効にします。LANの192.168.x.x:8791への直接接続は維持できます。", proxyDetectedTitle:"リバースプロキシを検出しました", proxyDetectedWarning:"現在、すべてのクライアントが1つのログイン制限枠を共有しています。ルーターがNASDrop 8791へ直接転送していないことを確認してから有効にしてください。", proxyEnabledWarning:"ルーターの公開ポートはNASDrop内部8791ではなく、DSMリバースプロキシのソースポートへ転送してください。", confirmReverseProxy:"DSMリバースプロキシが転送したクライアントIPを信頼しますか？ルーターの公開ポートがNASDrop 8791ではなくDSMプロキシのソースポートへ接続される場合のみ続行してください。", saveConnectionSettings:"接続設定を保存", connectionSettingsSaved:"接続設定を保存しました。DSMアイコンはルーターの公開ポート{port}を使用します。",
      downloadMethod:"ファイルごとのダウンロード方式", downloadMethodHint:"単一接続では分割・結合を省略し、共通の整合性検証は維持します。", method:"方式", segmentedMode:"8分割ダウンロード + 検証", singleMode:"単一接続 + 検証",
      singleModeWarningTitle:"単一接続の注意点", singleModeWarning:"1接続でサービスへの要求負荷を下げます。完了ファイルのサイズとハッシュは引き続き検証するため、検証中のディスク読み取りは発生します。", saveDownloadMethod:"ダウンロード方式を保存", singleModeShort:"単一接続", segmentedModeShort:"8分割 + 検証", downloadBehavior:"ダウンロード動作", downloadBehaviorHint:"同時実行数とファイルごとの接続方式をまとめて設定します。", combinedDownloadWarning:"並列または8分割ダウンロードはNASとネットワークの負荷を高める場合があります。", saveDownloadBehavior:"ダウンロード動作を保存", downloadBehaviorSaved:"ダウンロード動作の設定を保存しました。",
      sponsorTitle:"NASDropを支援", sponsorHint:"NASDropがお役に立った場合は、GitHub Sponsorsで継続的な開発を支援できます。", sponsorAction:"GitHubで支援する",
      folderTitle:"保存先フォルダーを選択", close:"閉じる", up:"上へ", cancel:"キャンセル", chooseThisFolder:"このフォルダーを選択", requestFailed:"リクエストを処理できませんでした。",
      error_auth_required:"ログインしてください。", error_invalid_credentials:"IDまたはパスワードが正しくありません。", error_account_not_configured:"NASDropアカウントがまだ設定されていません。", error_current_password_invalid:"現在のパスワードが正しくありません。", error_launcher_expired:"DSMアイコンの接続期限が切れました。アイコンを開き直してください。", error_permission_denied:"パッケージアカウントにこのフォルダーの権限がありません。", error_password_required:"アーカイブのパスワードが必要か、入力したパスワードが正しくありません。", error_rate_limited:"ダウンロードサービスが一時的に要求を制限しています。しばらくしてから再試行してください。", error_network_error:"ダウンロードサービスに接続できませんでした。", error_link_expired:"リンクの期限が切れているか利用できません。新しいリンクを追加してください。", error_integrity_failed:"整合性検証に失敗し、破損した一時データを削除しました。", error_archive_error:"アーカイブを安全に処理できませんでした。", error_invalid_link:"対応しているダウンロードリンクではありません。", error_invalid_job_state:"現在の状態ではこの操作を実行できません。", error_invalid_request:"入力内容を確認して再試行してください。", error_not_found:"要求された項目が見つかりません。", error_service_restarted:"サービスが再起動したためジョブを一時停止しました。再開できます。", error_internal_error:"内部処理中にエラーが発生しました。", error_generic_error:"リクエストを処理できませんでした。",
      error_invalid_username:"IDは半角英字、数字、ピリオド、アンダースコア、ハイフンを使用して3～32文字で入力してください。", error_invalid_password:"パスワードは制御文字を含めず10～128文字で入力してください。", error_too_many_attempts:"ログイン試行が多すぎます。約{minutes}分後に再試行してください。",
      error_login_temporarily_limited:"ログイン要求を一時的に制限しています。{seconds}秒後に再試行してください。",
      statusQueued:"待機中", statusReady:"準備完了", statusDownloading:"ダウンロード中", statusWaitingProcessing:"ディスク処理待ち", statusVerifying:"検証中", statusExtracting:"展開中", statusPublishing:"保存先へ移動中", statusPasswordRequired:"パスワードが必要", statusPaused:"一時停止", statusCompleted:"完了", statusFailed:"エラー", statusCancelled:"停止済み",
      writable:"書き込み可", permissionRequired:"権限が必要", notSelected:"未選択", packageWritable:"パッケージアカウントで書き込み可", dedicatedAccount:"パッケージ専用アカウント",
      gofileCooldown:"GoFile保護待機中 · {time}以降に自動再開します。繰り返し試行しないでください。", sameServiceSummary:"同一サービス最大{count}件", qrAlt:"NASDropクライアント接続QR", qrFailed:"QRを作成できません: {error}",
      processing:"{count}件処理中", noQueuedJobs:"待機中のジョブはありません", noJobsTitle:"ダウンロードジョブはありません。", noJobsHint:"リンクを追加すると、ここで進行状況を管理できます。", scheduled:"予約待機", integrity:"ファイル検証情報",
      confirmDelete:"選択した{count}件のジョブ履歴を削除しますか？", inspectLink:"リンクを確認中…", addedMany:"{count}ファイルを{target}のキューに追加しました。", addedOne:"{name}を{target}のキューに追加しました。",
      confirmClear:"完了した{count}件のジョブ履歴をすべて削除しますか？", confirmParallel:"同一サービスのジョブを最大{count}件同時実行しますか？速度制限やNAS負荷が増える場合があります。", saving:"保存中…",
      parallelSaved:"同一サービスのジョブを最大{count}件同時実行するよう設定しました。", sequentialSaved:"同一サービスのジョブは1件ずつ実行します。", loadingFolders:"フォルダーを読み込み中…",
      confirmSingleMode:"単一接続ダウンロードを使用しますか？サービスへの要求負荷を下げつつ、最終整合性検証は維持されます。", singleModeSaved:"新規および再開ジョブは単一接続と最終整合性検証を使用します。", segmentedModeSaved:"新規および再開ジョブは8分割ダウンロードと完全検証を使用します。",
      currentWritable:"このフォルダーに保存できます。", currentNotWritable:"この場所は選択できません。書き込み可能なサブフォルダーを選択してください。", browse:"開く", noSubfolders:"表示できるサブフォルダーはありません。",
      processingTitle:"一時フォルダーと展開", processingHint:"分割ファイルは非表示の作業領域でダウンロード・結合され、完成した結果だけが保存先に表示されます。", temporaryFolder:"一時フォルダー", archiveEngine:"展開エンジン", engineReady:"7-Zip準備完了", engineMissing:"エンジンなし", autoExtract:"新規ジョブの展開を既定にする", diskProtection:"ディスク処理中は新規ダウンロードを一時停止", archiveFormats:"ZIP、AES ZIP、7z、RAR、TAR系をアーカイブ名のフォルダーに展開します。", saveProcessing:"処理設定を保存", autoExtractOn:"既定の展開オン", autoExtractOff:"既定の展開オフ", processingSavedOn:"新規ジョブは展開が既定で、ジョブごとに変更できます。", processingSavedOff:"新規ジョブはアーカイブ保持が既定です。", archiveExtracted:"展開完了 · 元のアーカイブは一時領域でのみ使用", extractThisJob:"ダウンロード後に展開", archivePasswordOptional:"アーカイブのパスワード（任意）", archivePassword:"アーカイブのパスワード", retryExtraction:"展開を再試行",
      defaultChanged:"既定の保存先を{target}に変更しました。"
    },
    zh: {
      language:"语言", loginHint:"请使用在此服务器上设置的NASDrop ID和密码登录。从DSM图标打开时会自动登录。", httpWarningTitle:"未加密的HTTP连接", httpWarningBody:"NASDrop ID、密码和会话不会被加密。请仅在可信网络中使用HTTP；通过互联网访问时请配置HTTPS。", username:"ID", password:"密码", openDashboard:"打开控制面板", accountNotConfigured:"尚未设置账户。请通过DSM图标或Docker账户设置命令先创建ID和密码。", logout:"退出登录",
      dashboard:"控制面板", settings:"设置", runningOnNas:"正在NAS上运行", downloads:"下载", linkLabel:"支持的服务：GigaFile · GoFile · Pixeldrain · Buzzheavier", downloadNow:"下载到NAS",
      destination:"保存位置", checking:"正在检查…", checkingShort:"检查中", chooseFolder:"选择文件夹", jobs:"任务列表", loading:"正在加载…", clearCompleted:"清除已完成项",
      selected:"已选择{count}项", selectAll:"全选", clearSelection:"取消选择", pause:"暂停", resume:"继续", delete:"删除",
      clientConnection:"客户端连接", accountHint:"直接打开的浏览器和客户端应用使用此ID和密码登录。DSM图标仍会自动登录。", currentPassword:"当前密码", newPassword:"新密码", confirmPassword:"确认新密码", passwordRules:"请输入10至128个字符。系统不会保存密码原文，只保存加盐哈希。", saveAccount:"保存ID和密码", resetAccount:"重新设置", resetAccountHint:"请输入新的ID和密码后保存。现有客户端会话将全部退出。", passwordMismatch:"两次输入的新密码不一致。", accountSaved:"已保存客户端登录ID和密码。",
      defaultFolder:"默认保存位置", defaultFolderHint:"未另选文件夹时，任务将保存到此位置。", change:"更改", parallelTitle:"同一服务并行下载",
      parallelHint:"默认关闭。启用后，可同时启动GoFile等同一服务的多个任务。", allowParallel:"允许并行下载", sameServiceMax:"每个服务的最大数量",
      twoJobs:"2项", threeJobs:"3项", warning:"注意", parallelWarning:"在8段模式下，每个任务最多使用8个连接。3个活动任务最多会产生24个连接，可能增加限速、临时封禁以及NAS的CPU、磁盘和网络负载。",
      off:"关闭", saveParallel:"保存并行下载设置", folderPermissions:"文件夹权限", folderPermissionsHint:"无权访问的共享文件夹会显示为锁定。请在DSM共享文件夹权限中，向此套件的内部系统用户授予读写权限。",
      serviceAccount:"服务账户", serviceAddress:"连接路径", serviceAddressHint:"路由器公网端口、DSM反向代理端口和NASDrop内部端口具有不同的作用。", accessMethodHint:"DSM图标会自动登录。直接打开的浏览器和客户端应用必须输入ID和密码。", version:"版本", currentAccessAddress:"当前访问地址", launcherAddress:"DSM图标在当前主机上打开的地址",
      launcherPort:"路由器公网端口（DSM图标地址）", launcherPortHint:"这是互联网可见端口，不是DSM反向代理源端口或NASDrop内部端口。", connectionRouteTitle:"反向代理路径示例", connectionRoute:"互联网 :{publicPort} → 路由器 → 代理规则中设置的DSM HTTPS端口 → DSM反向代理 → NASDrop HTTP :{appPort}", connectionRouteHint:"即使两端都显示8791，路由器公网端口和NASDrop内部端口也承担不同作用。", saveLauncherPort:"保存图标端口", launcherPortSaved:"DSM图标将使用外部端口{port}。",
      reverseProxyMode:"信任DSM反向代理转发的真实客户端IP", reverseProxyHint:"当路由器将公网端口转发到DSM HTTPS，并由DSM代理到NASDrop HTTP 8791时启用。局域网192.168.x.x:8791直接访问可以保留。", proxyDetectedTitle:"检测到反向代理", proxyDetectedWarning:"当前所有客户端共用一个登录限制记录。确认路由器未直接转发到NASDrop 8791后再启用。", proxyEnabledWarning:"路由器公网端口必须指向DSM反向代理源端口，而不能直接指向NASDrop内部8791。", confirmReverseProxy:"要信任DSM反向代理转发的客户端IP吗？仅当路由器公网端口连接到DSM代理源端口而非NASDrop 8791时继续。", saveConnectionSettings:"保存连接设置", connectionSettingsSaved:"连接设置已保存。DSM图标将使用路由器公网端口{port}。",
      downloadMethod:"单个文件下载方式", downloadMethodHint:"单连接会跳过分段和合并，同时保留统一的完整性验证。", method:"方式", segmentedMode:"8段下载 + 验证", singleMode:"单连接 + 验证",
      singleModeWarningTitle:"单连接注意事项", singleModeWarning:"单个连接可降低服务请求压力。完成文件仍会检查大小和哈希，因此验证期间仍会读取磁盘。", saveDownloadMethod:"保存下载方式", singleModeShort:"单连接", segmentedModeShort:"8段 + 验证", downloadBehavior:"下载行为", downloadBehaviorHint:"统一设置并行数量和单文件连接方式。", combinedDownloadWarning:"并行或8段下载可能会增加NAS和网络负载。", saveDownloadBehavior:"保存下载行为", downloadBehaviorSaved:"下载行为设置已保存。",
      sponsorTitle:"支持NASDrop", sponsorHint:"如果NASDrop对您有帮助，可以通过GitHub Sponsors支持项目的持续开发。", sponsorAction:"在GitHub上支持",
      folderTitle:"选择保存文件夹", close:"关闭", up:"上一级", cancel:"取消", chooseThisFolder:"选择此文件夹", requestFailed:"无法完成请求。",
      error_auth_required:"请先登录。", error_invalid_credentials:"ID或密码不正确。", error_account_not_configured:"尚未配置NASDrop账户。", error_current_password_invalid:"当前密码不正确。", error_launcher_expired:"DSM图标连接已过期，请重新打开图标。", error_permission_denied:"套件账户没有此文件夹的权限。", error_password_required:"压缩包需要密码，或输入的密码不正确。", error_rate_limited:"下载服务暂时限制请求，请稍后重试。", error_network_error:"无法连接下载服务。", error_link_expired:"链接已过期或不可用，请添加新链接。", error_integrity_failed:"完整性验证失败，损坏的临时数据已删除。", error_archive_error:"无法安全处理压缩包。", error_invalid_link:"这不是受支持的下载链接。", error_invalid_job_state:"当前状态下无法执行此操作。", error_invalid_request:"请检查输入内容后重试。", error_not_found:"找不到请求的项目。", error_service_restarted:"服务已重启并暂停此任务，可以继续运行。", error_internal_error:"内部处理发生错误。", error_generic_error:"无法完成请求。",
      error_invalid_username:"ID须为3至32个字符，只能使用英文字母、数字、句点、下划线或连字符。", error_invalid_password:"密码须为10至128个字符，且不能包含控制字符。", error_too_many_attempts:"登录尝试次数过多，请约{minutes}分钟后重试。",
      error_login_temporarily_limited:"登录请求暂时受限，请在{seconds}秒后重试。",
      statusQueued:"等待中", statusReady:"准备就绪", statusDownloading:"下载中", statusWaitingProcessing:"等待磁盘处理", statusVerifying:"验证中", statusExtracting:"正在解压", statusPublishing:"正在移至保存位置", statusPasswordRequired:"需要密码", statusPaused:"已暂停", statusCompleted:"已完成", statusFailed:"错误", statusCancelled:"已停止",
      writable:"可写", permissionRequired:"需要权限", notSelected:"未选择", packageWritable:"套件账户可写", dedicatedAccount:"套件专用账户",
      gofileCooldown:"GoFile保护等待中 · 将在{time}后自动恢复。请勿反复重试。", sameServiceSummary:"同一服务最多{count}项", qrAlt:"NASDrop客户端连接二维码", qrFailed:"无法生成二维码：{error}",
      processing:"正在处理{count}项", noQueuedJobs:"没有等待中的任务", noJobsTitle:"没有下载任务。", noJobsHint:"添加链接后可在此管理进度。", scheduled:"计划等待", integrity:"文件验证信息",
      confirmDelete:"要删除所选的{count}条任务记录吗？", inspectLink:"正在检查链接…", addedMany:"已将{count}个文件添加到{target}队列。", addedOne:"已将{name}添加到{target}队列。",
      confirmClear:"要删除全部{count}条已完成任务记录吗？", confirmParallel:"要同时运行最多{count}个同一服务的任务吗？限速风险和NAS负载可能增加。", saving:"正在保存…",
      parallelSaved:"已设置同一服务最多并行运行{count}个任务。", sequentialSaved:"同一服务的任务将逐个运行。", loadingFolders:"正在加载文件夹…",
      confirmSingleMode:"要使用单连接下载吗？这会降低服务请求压力，同时保留最终完整性验证。", singleModeSaved:"新建和继续的任务将使用单连接和最终完整性验证。", segmentedModeSaved:"新建和继续的任务将使用8段下载和完整验证。",
      currentWritable:"可以保存到当前文件夹。", currentNotWritable:"无法选择当前位置。请选择可写的子文件夹。", browse:"浏览", noSubfolders:"没有可显示的子文件夹。",
      processingTitle:"临时文件夹和解压", processingHint:"分片在隐藏工作区中下载并合并，保存位置只显示完整结果。", temporaryFolder:"临时文件夹", archiveEngine:"解压引擎", engineReady:"7-Zip已就绪", engineMissing:"缺少引擎", autoExtract:"新任务默认解压", diskProtection:"磁盘处理期间暂停新下载", archiveFormats:"ZIP、AES ZIP、7z、RAR和TAR系列会解压到同名文件夹。", saveProcessing:"保存处理设置", autoExtractOn:"默认解压开启", autoExtractOff:"默认解压关闭", processingSavedOn:"新任务默认解压，并可逐任务更改。", processingSavedOff:"新任务默认保留压缩文件。", archiveExtracted:"解压完成 · 原压缩文件仅在临时空间中使用", extractThisJob:"下载后解压", archivePasswordOptional:"压缩密码（可选）", archivePassword:"压缩密码", retryExtraction:"重试解压",
      defaultChanged:"默认保存位置已更改为{target}。"
    }
  };

  const supported = Object.keys(messages);
  function normalize(value) {
    const code = String(value || "").toLowerCase().split("-")[0];
    return supported.includes(code) ? code : "en";
  }
  function detect() {
    const saved = localStorage.getItem("nasdrop-language");
    if (saved && supported.includes(saved)) return saved;
    for (const value of navigator.languages || [navigator.language]) {
      const code = normalize(value);
      if (code !== "en" || String(value || "").toLowerCase().startsWith("en")) return code;
    }
    return "en";
  }
  let language = detect();
  function t(key, vars = {}) {
    let value = messages[language][key] ?? messages.en[key] ?? key;
    Object.entries(vars).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); });
    return value;
  }
  function error(code, fallback = "", vars = {}) {
    if (language === "ko" && fallback) return String(fallback);
    const key = `error_${String(code || "generic_error")}`;
    let value = messages[language][key] ?? messages.en[key] ?? t("error_generic_error");
    Object.entries(vars || {}).forEach(([name, replacement]) => { value = value.replaceAll(`{${name}}`, String(replacement)); });
    return value;
  }
  function apply() {
    document.documentElement.lang = language === "zh" ? "zh-CN" : language;
    document.querySelectorAll("[data-i18n]").forEach(node => { node.textContent = t(node.dataset.i18n); });
    document.querySelectorAll("[data-i18n-placeholder]").forEach(node => { node.placeholder = t(node.dataset.i18nPlaceholder); });
    document.querySelectorAll("[data-i18n-aria-label]").forEach(node => { node.setAttribute("aria-label", t(node.dataset.i18nAriaLabel)); });
    document.querySelectorAll("[data-language-select]").forEach(node => { node.value = language; });
  }
  function setLanguage(value) {
    language = normalize(value);
    localStorage.setItem("nasdrop-language", language);
    apply();
    window.dispatchEvent(new CustomEvent("nasdrop-language-change"));
  }
  window.NASDropI18n = { t, error, apply, setLanguage, get language() { return language; } };
  document.querySelectorAll("[data-language-select]").forEach(node => node.addEventListener("change", event => setLanguage(event.target.value)));
  apply();
})();
